{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-mail",
    "version": "3.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context-support",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.eclipse.angus",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-mail-3.2.5.jar",
          "url": "spring-boot-starter-mail-3.2.5.jar",
          "size": 4774,
          "sha512": "8b4b4acf4bfaf2ce85c7435ebdaee0d7249bb9cb0cc30f9745767e5a68c2b846d9e7ebdcd35473915725bdc7616323144aadbb4118ef84faff5b9832caaae3aa",
          "sha256": "655ca0fc21b2abba0b860b1d83daa6c6b7311da0ecaa91ef43776d78ab5183c9",
          "sha1": "19fbf3b0760caef5ae64d499161121b7969ba2b6",
          "md5": "44f4f47ca23aecdc3d2025634ef31100"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context-support",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.eclipse.angus",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-mail-3.2.5.jar",
          "url": "spring-boot-starter-mail-3.2.5.jar",
          "size": 4774,
          "sha512": "8b4b4acf4bfaf2ce85c7435ebdaee0d7249bb9cb0cc30f9745767e5a68c2b846d9e7ebdcd35473915725bdc7616323144aadbb4118ef84faff5b9832caaae3aa",
          "sha256": "655ca0fc21b2abba0b860b1d83daa6c6b7311da0ecaa91ef43776d78ab5183c9",
          "sha1": "19fbf3b0760caef5ae64d499161121b7969ba2b6",
          "md5": "44f4f47ca23aecdc3d2025634ef31100"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-mail-3.2.5.jar",
          "url": "spring-boot-starter-mail-3.2.5.jar",
          "size": 4774,
          "sha512": "8b4b4acf4bfaf2ce85c7435ebdaee0d7249bb9cb0cc30f9745767e5a68c2b846d9e7ebdcd35473915725bdc7616323144aadbb4118ef84faff5b9832caaae3aa",
          "sha256": "655ca0fc21b2abba0b860b1d83daa6c6b7311da0ecaa91ef43776d78ab5183c9",
          "sha1": "19fbf3b0760caef5ae64d499161121b7969ba2b6",
          "md5": "44f4f47ca23aecdc3d2025634ef31100"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-mail-maven-optional",
          "version": "3.2.5"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-mail-3.2.5.jar",
          "url": "spring-boot-starter-mail-3.2.5.jar",
          "size": 4774,
          "sha512": "8b4b4acf4bfaf2ce85c7435ebdaee0d7249bb9cb0cc30f9745767e5a68c2b846d9e7ebdcd35473915725bdc7616323144aadbb4118ef84faff5b9832caaae3aa",
          "sha256": "655ca0fc21b2abba0b860b1d83daa6c6b7311da0ecaa91ef43776d78ab5183c9",
          "sha1": "19fbf3b0760caef5ae64d499161121b7969ba2b6",
          "md5": "44f4f47ca23aecdc3d2025634ef31100"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-mail-maven-optional",
          "version": "3.2.5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-mail-3.2.5-javadoc.jar",
          "url": "spring-boot-starter-mail-3.2.5-javadoc.jar",
          "size": 4741,
          "sha512": "327b6cd2a438cde71b9448de4b07190be0d6e0dfc369ce5795f1eccd5b351fe845b442e83782e21f56ad06c110bd65b8de5cb6ec7b14cbd5f44acb1741ee4abb",
          "sha256": "a9ce57121dec82395bf6e410d5df4a969943ae402900561b1bcd814609244b87",
          "sha1": "40db9854076775f9b9f3eac8840239274ad8c206",
          "md5": "aa2c904194b80967fae3fb2c33471121"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-mail-3.2.5-sources.jar",
          "url": "spring-boot-starter-mail-3.2.5-sources.jar",
          "size": 4740,
          "sha512": "d234ef4c5d8c91ac585613326ac953a517cc9972f9cdcd33bf307486a09f800ac273660f4a437e5b4ff54004990a3a2d3f199b93466d40e7a10cd38aaf52e130",
          "sha256": "bab08b4c61b5899a75702b8e4049e337ee7cee1847d43f039df907d2870075ef",
          "sha1": "681fd0ea1a3e1a512b011bd3056628a9f5f59391",
          "md5": "5eee8e5586724911e7e73cec78c22b35"
        }
      ]
    }
  ]
}
